### ISSUE TITLE
Thinking of using sf instead of sp

### ISSUE THREAD

**Issue by Nowosad** [dabrowskia/dspace#2]

**Comment by dabrowskia** [comment]
Some functions from used packages are bound do sp...

**Comment by Nowosad** [comment]
Which packages? Which functions?

**Comment by dabrowskia** [comment]
Nevermind. I've changed it to work only with sf ;) . My assumption was from 2 years ago. It should work on branch sp2sf.

**Comment by Nowosad** [comment]
Neat.

**Comment by Nowosad** [comment]
Btw @dabrowskia - merge my pull request (https://github.com/dabrowskia/dspace/pull/14) with your branch.

**Comment by dabrowskia** [comment]
done
